#Minecraft server properties
#Wed Oct 07 12:53:39 CEST 2026
allow-flight=false
allow-nether=true
announce-player-achievements=true
difficulty=0
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=1
generate-structures=false
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=FLAT
max-build-height=256
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=mcscon test 1.11
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=127.0.0.1
server-port=25613
snooper-enabled=true
spawn-animals=true
spawn-monsters=false
spawn-npcs=true
view-distance=4
white-list=false
