// GENERATED by tools/gen_packets.py from minecraft-data - do not edit
#pragma once
#include "wire.h"
#include "ids_gen.h"
namespace mc { namespace sb {
template<class T> struct Opt { bool has; T v; Opt() : has(false), v() {} };

struct Abilities {
    static ids::PlaySb packetId() { return ids::PlaySb::Abilities; }
    i8 flags;
    float flyingSpeed;
    float walkingSpeed;
};

static const u8 kVar_Abilities[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Abilities& o, Version v) {
    switch (kVar_Abilities[(int)v]) {
    case 0: {
        w.u8_((u8)o.flags);
        w.f32_(o.flyingSpeed);
        w.f32_(o.walkingSpeed);
        break; }
    default: return false;
    }
    return !w.err;
}

struct AdvancementTab {
    static ids::PlaySb packetId() { return ids::PlaySb::AdvancementTab; }
    i32 action;
    StrView tabId;
};

static const u8 kVar_AdvancementTab[6] = {255,255,255,0,0,0};
inline bool encode(Writer& w, const AdvancementTab& o, Version v) {
    switch (kVar_AdvancementTab[(int)v]) {
    case 0: {
        w.varint(o.action);
        if (o.action == 0) {
            w.str(o.tabId);
        }
        break; }
    default: return false;
    }
    return !w.err;
}

struct ArmAnimation {
    static ids::PlaySb packetId() { return ids::PlaySb::ArmAnimation; }
    i32 hand;
};

static const u8 kVar_ArmAnimation[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const ArmAnimation& o, Version v) {
    switch (kVar_ArmAnimation[(int)v]) {
    case 0: {
        w.varint(o.hand);
        break; }
    default: return false;
    }
    return !w.err;
}

struct BlockDig {
    static ids::PlaySb packetId() { return ids::PlaySb::BlockDig; }
    i32 status;
    BlockPos location;
    i8 face;
};

static const u8 kVar_BlockDig[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const BlockDig& o, Version v) {
    switch (kVar_BlockDig[(int)v]) {
    case 0: {
        w.varint(o.status);
        w.u64_(packPos(o.location.x, o.location.y, o.location.z));
        w.u8_((u8)o.face);
        break; }
    default: return false;
    }
    return !w.err;
}

struct BlockPlace {
    static ids::PlaySb packetId() { return ids::PlaySb::BlockPlace; }
    BlockPos location;
    i32 direction;
    i32 hand;
    float cursorX;
    float cursorY;
    float cursorZ;
};

static const u8 kVar_BlockPlace[6] = {0,1,1,1,1,1};
inline bool encode(Writer& w, const BlockPlace& o, Version v) {
    switch (kVar_BlockPlace[(int)v]) {
    case 0: {
        w.u64_(packPos(o.location.x, o.location.y, o.location.z));
        w.varint(o.direction);
        w.varint(o.hand);
        w.u8_((u8)o.cursorX);
        w.u8_((u8)o.cursorY);
        w.u8_((u8)o.cursorZ);
        break; }
    case 1: {
        w.u64_(packPos(o.location.x, o.location.y, o.location.z));
        w.varint(o.direction);
        w.varint(o.hand);
        w.f32_(o.cursorX);
        w.f32_(o.cursorY);
        w.f32_(o.cursorZ);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Chat {
    static ids::PlaySb packetId() { return ids::PlaySb::Chat; }
    StrView message;
};

static const u8 kVar_Chat[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Chat& o, Version v) {
    switch (kVar_Chat[(int)v]) {
    case 0: {
        w.str(o.message);
        break; }
    default: return false;
    }
    return !w.err;
}

struct ClientCommand {
    static ids::PlaySb packetId() { return ids::PlaySb::ClientCommand; }
    i32 actionId;
};

static const u8 kVar_ClientCommand[6] = {0,0,0,1,1,1};
inline bool encode(Writer& w, const ClientCommand& o, Version v) {
    switch (kVar_ClientCommand[(int)v]) {
    case 0: {
        w.varint(o.actionId);
        break; }
    case 1: {
        w.varint(o.actionId);
        break; }
    default: return false;
    }
    return !w.err;
}

struct CloseWindow {
    static ids::PlaySb packetId() { return ids::PlaySb::CloseWindow; }
    u8 windowId;
};

static const u8 kVar_CloseWindow[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const CloseWindow& o, Version v) {
    switch (kVar_CloseWindow[(int)v]) {
    case 0: {
        w.u8_(o.windowId);
        break; }
    default: return false;
    }
    return !w.err;
}

struct CraftRecipeRequest {
    static ids::PlaySb packetId() { return ids::PlaySb::CraftRecipeRequest; }
    i8 windowId;
    i32 recipe;
    bool makeAll;
};

static const u8 kVar_CraftRecipeRequest[6] = {255,255,255,255,0,0};
inline bool encode(Writer& w, const CraftRecipeRequest& o, Version v) {
    switch (kVar_CraftRecipeRequest[(int)v]) {
    case 0: {
        w.u8_((u8)o.windowId);
        w.varint(o.recipe);
        w.bool_(o.makeAll);
        break; }
    default: return false;
    }
    return !w.err;
}

struct CraftingBookData {
    static ids::PlaySb packetId() { return ids::PlaySb::CraftingBookData; }
    i32 type;
    i32 displayedRecipe;
    bool craftingBookOpen;
    bool craftingFilter;
};

static const u8 kVar_CraftingBookData[6] = {255,255,255,0,0,0};
inline bool encode(Writer& w, const CraftingBookData& o, Version v) {
    switch (kVar_CraftingBookData[(int)v]) {
    case 0: {
        w.varint(o.type);
        if (o.type == 0) {
            w.i32_(o.displayedRecipe);
        }
        if (o.type == 1) {
            w.bool_(o.craftingBookOpen);
            w.bool_(o.craftingFilter);
        }
        break; }
    default: return false;
    }
    return !w.err;
}

struct CustomPayload {
    static ids::PlaySb packetId() { return ids::PlaySb::CustomPayload; }
    StrView channel;
    Bytes data;
};

static const u8 kVar_CustomPayload[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const CustomPayload& o, Version v) {
    switch (kVar_CustomPayload[(int)v]) {
    case 0: {
        w.str(o.channel);
        w.bytes(o.data.data, o.data.len);
        break; }
    default: return false;
    }
    return !w.err;
}

struct EnchantItem {
    static ids::PlaySb packetId() { return ids::PlaySb::EnchantItem; }
    i8 windowId;
    i8 enchantment;
};

static const u8 kVar_EnchantItem[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const EnchantItem& o, Version v) {
    switch (kVar_EnchantItem[(int)v]) {
    case 0: {
        w.u8_((u8)o.windowId);
        w.u8_((u8)o.enchantment);
        break; }
    default: return false;
    }
    return !w.err;
}

struct EntityAction {
    static ids::PlaySb packetId() { return ids::PlaySb::EntityAction; }
    i32 entityId;
    i32 actionId;
    i32 jumpBoost;
};

static const u8 kVar_EntityAction[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const EntityAction& o, Version v) {
    switch (kVar_EntityAction[(int)v]) {
    case 0: {
        w.varint(o.entityId);
        w.varint(o.actionId);
        w.varint(o.jumpBoost);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Flying {
    static ids::PlaySb packetId() { return ids::PlaySb::Flying; }
    bool onGround;
};

static const u8 kVar_Flying[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Flying& o, Version v) {
    switch (kVar_Flying[(int)v]) {
    case 0: {
        w.bool_(o.onGround);
        break; }
    default: return false;
    }
    return !w.err;
}

struct HeldItemSlot {
    static ids::PlaySb packetId() { return ids::PlaySb::HeldItemSlot; }
    i16 slotId;
};

static const u8 kVar_HeldItemSlot[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const HeldItemSlot& o, Version v) {
    switch (kVar_HeldItemSlot[(int)v]) {
    case 0: {
        w.u16_((u16)o.slotId);
        break; }
    default: return false;
    }
    return !w.err;
}

struct KeepAlive {
    static ids::PlaySb packetId() { return ids::PlaySb::KeepAlive; }
    i64 keepAliveId;
};

static const u8 kVar_KeepAlive[6] = {0,0,0,0,0,1};
inline bool encode(Writer& w, const KeepAlive& o, Version v) {
    switch (kVar_KeepAlive[(int)v]) {
    case 0: {
        w.varint(o.keepAliveId);
        break; }
    case 1: {
        w.i64_(o.keepAliveId);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Look {
    static ids::PlaySb packetId() { return ids::PlaySb::Look; }
    float yaw;
    float pitch;
    bool onGround;
};

static const u8 kVar_Look[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Look& o, Version v) {
    switch (kVar_Look[(int)v]) {
    case 0: {
        w.f32_(o.yaw);
        w.f32_(o.pitch);
        w.bool_(o.onGround);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Position {
    static ids::PlaySb packetId() { return ids::PlaySb::Position; }
    double x;
    double y;
    double z;
    bool onGround;
};

static const u8 kVar_Position[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Position& o, Version v) {
    switch (kVar_Position[(int)v]) {
    case 0: {
        w.f64_(o.x);
        w.f64_(o.y);
        w.f64_(o.z);
        w.bool_(o.onGround);
        break; }
    default: return false;
    }
    return !w.err;
}

struct PositionLook {
    static ids::PlaySb packetId() { return ids::PlaySb::PositionLook; }
    double x;
    double y;
    double z;
    float yaw;
    float pitch;
    bool onGround;
};

static const u8 kVar_PositionLook[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const PositionLook& o, Version v) {
    switch (kVar_PositionLook[(int)v]) {
    case 0: {
        w.f64_(o.x);
        w.f64_(o.y);
        w.f64_(o.z);
        w.f32_(o.yaw);
        w.f32_(o.pitch);
        w.bool_(o.onGround);
        break; }
    default: return false;
    }
    return !w.err;
}

struct PrepareCraftingGrid_returnEntry {
    Slot item;
    u8 craftingSlot;
    u8 playerSlot;
};

struct PrepareCraftingGrid_prepareEntry {
    Slot item;
    u8 craftingSlot;
    u8 playerSlot;
};

inline void encodeElem(Writer& w, const PrepareCraftingGrid_returnEntry& o, Version v, i32 ctx) {
    (void)v; (void)ctx;
    encodeSlot(w, o.item);
    w.u8_(o.craftingSlot);
    w.u8_(o.playerSlot);
}

inline void encodeElem(Writer& w, const PrepareCraftingGrid_prepareEntry& o, Version v, i32 ctx) {
    (void)v; (void)ctx;
    encodeSlot(w, o.item);
    w.u8_(o.craftingSlot);
    w.u8_(o.playerSlot);
}

struct PrepareCraftingGrid {
    static ids::PlaySb packetId() { return ids::PlaySb::PrepareCraftingGrid; }
    u8 windowId;
    u16 actionNumber;
    Span<PrepareCraftingGrid_returnEntry> returnEntry;
    Span<PrepareCraftingGrid_prepareEntry> prepareEntry;
};

static const u8 kVar_PrepareCraftingGrid[6] = {255,255,255,0,255,255};
inline bool encode(Writer& w, const PrepareCraftingGrid& o, Version v) {
    switch (kVar_PrepareCraftingGrid[(int)v]) {
    case 0: {
        w.u8_(o.windowId);
        w.u16_(o.actionNumber);
        w.u16_((u16)o.returnEntry.n);
        for (u32 j = 0; j < o.returnEntry.n; ++j) encodeElem(w, o.returnEntry.data[j], v, 0);
        w.u16_((u16)o.prepareEntry.n);
        for (u32 j = 0; j < o.prepareEntry.n; ++j) encodeElem(w, o.prepareEntry.data[j], v, 0);
        break; }
    default: return false;
    }
    return !w.err;
}

struct ResourcePackReceive {
    static ids::PlaySb packetId() { return ids::PlaySb::ResourcePackReceive; }
    i32 result;
};

static const u8 kVar_ResourcePackReceive[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const ResourcePackReceive& o, Version v) {
    switch (kVar_ResourcePackReceive[(int)v]) {
    case 0: {
        w.varint(o.result);
        break; }
    default: return false;
    }
    return !w.err;
}

struct SetCreativeSlot {
    static ids::PlaySb packetId() { return ids::PlaySb::SetCreativeSlot; }
    i16 slot;
    Slot item;
};

static const u8 kVar_SetCreativeSlot[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const SetCreativeSlot& o, Version v) {
    switch (kVar_SetCreativeSlot[(int)v]) {
    case 0: {
        w.u16_((u16)o.slot);
        encodeSlot(w, o.item);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Settings {
    static ids::PlaySb packetId() { return ids::PlaySb::Settings; }
    StrView locale;
    i8 viewDistance;
    i32 chatFlags;
    bool chatColors;
    u8 skinParts;
    i32 mainHand;
};

static const u8 kVar_Settings[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Settings& o, Version v) {
    switch (kVar_Settings[(int)v]) {
    case 0: {
        w.str(o.locale);
        w.u8_((u8)o.viewDistance);
        w.varint(o.chatFlags);
        w.bool_(o.chatColors);
        w.u8_(o.skinParts);
        w.varint(o.mainHand);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Spectate {
    static ids::PlaySb packetId() { return ids::PlaySb::Spectate; }
    Uuid target;
};

static const u8 kVar_Spectate[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Spectate& o, Version v) {
    switch (kVar_Spectate[(int)v]) {
    case 0: {
        w.bytes(o.target.b, 16);
        break; }
    default: return false;
    }
    return !w.err;
}

struct SteerBoat {
    static ids::PlaySb packetId() { return ids::PlaySb::SteerBoat; }
    bool leftPaddle;
    bool rightPaddle;
};

static const u8 kVar_SteerBoat[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const SteerBoat& o, Version v) {
    switch (kVar_SteerBoat[(int)v]) {
    case 0: {
        w.bool_(o.leftPaddle);
        w.bool_(o.rightPaddle);
        break; }
    default: return false;
    }
    return !w.err;
}

struct SteerVehicle {
    static ids::PlaySb packetId() { return ids::PlaySb::SteerVehicle; }
    float sideways;
    float forward;
    u8 jump;
};

static const u8 kVar_SteerVehicle[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const SteerVehicle& o, Version v) {
    switch (kVar_SteerVehicle[(int)v]) {
    case 0: {
        w.f32_(o.sideways);
        w.f32_(o.forward);
        w.u8_(o.jump);
        break; }
    default: return false;
    }
    return !w.err;
}

struct TabComplete {
    static ids::PlaySb packetId() { return ids::PlaySb::TabComplete; }
    StrView text;
    bool assumeCommand;
    Opt<BlockPos> lookedAtBlock;
};

static const u8 kVar_TabComplete[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const TabComplete& o, Version v) {
    switch (kVar_TabComplete[(int)v]) {
    case 0: {
        w.str(o.text);
        w.bool_(o.assumeCommand);
        w.bool_(o.lookedAtBlock.has);
        if (o.lookedAtBlock.has) {
            w.u64_(packPos(o.lookedAtBlock.v.x, o.lookedAtBlock.v.y, o.lookedAtBlock.v.z));
        }
        break; }
    default: return false;
    }
    return !w.err;
}

struct TeleportConfirm {
    static ids::PlaySb packetId() { return ids::PlaySb::TeleportConfirm; }
    i32 teleportId;
};

static const u8 kVar_TeleportConfirm[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const TeleportConfirm& o, Version v) {
    switch (kVar_TeleportConfirm[(int)v]) {
    case 0: {
        w.varint(o.teleportId);
        break; }
    default: return false;
    }
    return !w.err;
}

struct Transaction {
    static ids::PlaySb packetId() { return ids::PlaySb::Transaction; }
    i8 windowId;
    i16 action;
    bool accepted;
};

static const u8 kVar_Transaction[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const Transaction& o, Version v) {
    switch (kVar_Transaction[(int)v]) {
    case 0: {
        w.u8_((u8)o.windowId);
        w.u16_((u16)o.action);
        w.bool_(o.accepted);
        break; }
    default: return false;
    }
    return !w.err;
}

struct UpdateSign {
    static ids::PlaySb packetId() { return ids::PlaySb::UpdateSign; }
    BlockPos location;
    StrView text1;
    StrView text2;
    StrView text3;
    StrView text4;
};

static const u8 kVar_UpdateSign[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const UpdateSign& o, Version v) {
    switch (kVar_UpdateSign[(int)v]) {
    case 0: {
        w.u64_(packPos(o.location.x, o.location.y, o.location.z));
        w.str(o.text1);
        w.str(o.text2);
        w.str(o.text3);
        w.str(o.text4);
        break; }
    default: return false;
    }
    return !w.err;
}

struct UseEntity {
    static ids::PlaySb packetId() { return ids::PlaySb::UseEntity; }
    i32 target;
    i32 mouse;
    float x;
    float y;
    float z;
    i32 hand;
};

static const u8 kVar_UseEntity[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const UseEntity& o, Version v) {
    switch (kVar_UseEntity[(int)v]) {
    case 0: {
        w.varint(o.target);
        w.varint(o.mouse);
        if (o.mouse == 2) {
            w.f32_(o.x);
        }
        if (o.mouse == 2) {
            w.f32_(o.y);
        }
        if (o.mouse == 2) {
            w.f32_(o.z);
        }
        if (o.mouse == 0 || o.mouse == 2) {
            w.varint(o.hand);
        }
        break; }
    default: return false;
    }
    return !w.err;
}

struct UseItem {
    static ids::PlaySb packetId() { return ids::PlaySb::UseItem; }
    i32 hand;
};

static const u8 kVar_UseItem[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const UseItem& o, Version v) {
    switch (kVar_UseItem[(int)v]) {
    case 0: {
        w.varint(o.hand);
        break; }
    default: return false;
    }
    return !w.err;
}

struct VehicleMove {
    static ids::PlaySb packetId() { return ids::PlaySb::VehicleMove; }
    double x;
    double y;
    double z;
    float yaw;
    float pitch;
};

static const u8 kVar_VehicleMove[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const VehicleMove& o, Version v) {
    switch (kVar_VehicleMove[(int)v]) {
    case 0: {
        w.f64_(o.x);
        w.f64_(o.y);
        w.f64_(o.z);
        w.f32_(o.yaw);
        w.f32_(o.pitch);
        break; }
    default: return false;
    }
    return !w.err;
}

struct WindowClick {
    static ids::PlaySb packetId() { return ids::PlaySb::WindowClick; }
    u8 windowId;
    i16 slot;
    i8 mouseButton;
    i16 action;
    i8 mode;
    Slot item;
};

static const u8 kVar_WindowClick[6] = {0,0,0,0,0,0};
inline bool encode(Writer& w, const WindowClick& o, Version v) {
    switch (kVar_WindowClick[(int)v]) {
    case 0: {
        w.u8_(o.windowId);
        w.u16_((u16)o.slot);
        w.u8_((u8)o.mouseButton);
        w.u16_((u16)o.action);
        w.u8_((u8)o.mode);
        encodeSlot(w, o.item);
        break; }
    default: return false;
    }
    return !w.err;
}

}} // namespace mc::sb
