// GENERATED by tools/gen_packets.py from minecraft-data - do not edit
#pragma once
#include "wire.h"
#include "ids_gen.h"
namespace mc { namespace cb {
template<class T> struct Opt { bool has; T v; Opt() : has(false), v() {} };

struct Abilities {
    static ids::PlayCb packetId() { return ids::PlayCb::Abilities; }
    i8 flags;
    float flyingSpeed;
    float walkingSpeed;
};

static const u8 kVar_Abilities[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Abilities& o, Version v) {
    o = Abilities();
    switch (kVar_Abilities[(int)v]) {
    case 0: {
        o.flags = r.i8_();
        o.flyingSpeed = r.f32_();
        o.walkingSpeed = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Advancements_advancementMapping_value_displayData_v {
    StrView title;
    StrView description;
    Slot icon;
    i32 frameType;
    u32 flags;
    StrView backgroundTexture;
    float xCord;
    float yCord;
};

struct Advancements_advancementMapping_value_criteria {
    StrView key;
};

struct Advancements_advancementMapping_value {
    Opt<StrView> parentId;
    Opt<Advancements_advancementMapping_value_displayData_v> displayData;
    Array<Advancements_advancementMapping_value_criteria> criteria;
    Array<Array<StrView>> requirements;
};

struct Advancements_advancementMapping {
    StrView key;
    Advancements_advancementMapping_value value;
};

struct Advancements_progressMapping_value {
    StrView criterionIdentifier;
    Opt<i64> criterionProgress;
};

struct Advancements_progressMapping {
    StrView key;
    Array<Advancements_progressMapping_value> value;
};

inline bool decodeElem(Reader& r, Advancements_advancementMapping_value_displayData_v& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_advancementMapping_value_displayData_v();
    o.title = r.str();
    o.description = r.str();
    if (!decodeSlot(r, o.icon)) return false;
    o.frameType = r.varint();
    o.flags = r.u32_();
    if ((((o.flags) >> 0) & 1) == 1) {
        o.backgroundTexture = r.str();
    }
    o.xCord = r.f32_();
    o.yCord = r.f32_();
    return r.ok();
}

inline bool decodeElem(Reader& r, Advancements_advancementMapping_value_criteria& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_advancementMapping_value_criteria();
    o.key = r.str();
    return r.ok();
}

inline bool decodeElem(Reader& r, Advancements_advancementMapping_value& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_advancementMapping_value();
    o.parentId.has = r.bool_();
    if (o.parentId.has) {
        o.parentId.v = r.str();
    }
    o.displayData.has = r.bool_();
    if (o.displayData.has) {
        if (!decodeElem(r, o.displayData.v, v, 0)) return false;
    }
    { i32 n = r.varint();
        if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
        o.criteria.r = r; o.criteria.r.err = false; o.criteria.n = (u32)n; o.criteria.v = v; o.criteria.ctx = 0;
        Advancements_advancementMapping_value_criteria tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
        o.criteria.r.end = r.p; }
    { i32 n = r.varint();
        if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
        o.requirements.r = r; o.requirements.r.err = false; o.requirements.n = (u32)n; o.requirements.v = v; o.requirements.ctx = 0;
        Array<StrView> tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
        o.requirements.r.end = r.p; }
    return r.ok();
}

inline bool decodeElem(Reader& r, Advancements_advancementMapping& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_advancementMapping();
    o.key = r.str();
    if (!decodeElem(r, o.value, v, 0)) return false;
    return r.ok();
}

inline bool decodeElem(Reader& r, Advancements_progressMapping_value& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_progressMapping_value();
    o.criterionIdentifier = r.str();
    o.criterionProgress.has = r.bool_();
    if (o.criterionProgress.has) {
        o.criterionProgress.v = r.i64_();
    }
    return r.ok();
}

inline bool decodeElem(Reader& r, Advancements_progressMapping& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Advancements_progressMapping();
    o.key = r.str();
    { i32 n = r.varint();
        if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
        o.value.r = r; o.value.r.err = false; o.value.n = (u32)n; o.value.v = v; o.value.ctx = 0;
        Advancements_progressMapping_value tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
        o.value.r.end = r.p; }
    return r.ok();
}

struct Advancements {
    static ids::PlayCb packetId() { return ids::PlayCb::Advancements; }
    bool reset;
    Array<Advancements_advancementMapping> advancementMapping;
    Array<StrView> identifiers;
    Array<Advancements_progressMapping> progressMapping;
};

static const u8 kVar_Advancements[6] = {255,255,255,0,0,0};
inline bool decode(Reader& r, Advancements& o, Version v) {
    o = Advancements();
    switch (kVar_Advancements[(int)v]) {
    case 0: {
        o.reset = r.bool_();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.advancementMapping.r = r; o.advancementMapping.r.err = false; o.advancementMapping.n = (u32)n; o.advancementMapping.v = v; o.advancementMapping.ctx = 0;
            Advancements_advancementMapping tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.advancementMapping.r.end = r.p; }
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.identifiers.r = r; o.identifiers.r.err = false; o.identifiers.n = (u32)n; o.identifiers.v = v; o.identifiers.ctx = 0;
            StrView tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.identifiers.r.end = r.p; }
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.progressMapping.r = r; o.progressMapping.r.err = false; o.progressMapping.n = (u32)n; o.progressMapping.v = v; o.progressMapping.ctx = 0;
            Advancements_progressMapping tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.progressMapping.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct Animation {
    static ids::PlayCb packetId() { return ids::PlayCb::Animation; }
    i32 entityId;
    u8 animation;
};

static const u8 kVar_Animation[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Animation& o, Version v) {
    o = Animation();
    switch (kVar_Animation[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.animation = r.u8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct AttachEntity {
    static ids::PlayCb packetId() { return ids::PlayCb::AttachEntity; }
    i32 entityId;
    i32 vehicleId;
};

static const u8 kVar_AttachEntity[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, AttachEntity& o, Version v) {
    o = AttachEntity();
    switch (kVar_AttachEntity[(int)v]) {
    case 0: {
        o.entityId = r.i32_();
        o.vehicleId = r.i32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Bed {
    static ids::PlayCb packetId() { return ids::PlayCb::Bed; }
    i32 entityId;
    BlockPos location;
};

static const u8 kVar_Bed[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Bed& o, Version v) {
    o = Bed();
    switch (kVar_Bed[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.location = unpackPos(r.u64_());
        break; }
    default: return false;
    }
    return r.ok();
}

struct BlockAction {
    static ids::PlayCb packetId() { return ids::PlayCb::BlockAction; }
    BlockPos location;
    u8 byte1;
    u8 byte2;
    i32 blockId;
};

static const u8 kVar_BlockAction[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, BlockAction& o, Version v) {
    o = BlockAction();
    switch (kVar_BlockAction[(int)v]) {
    case 0: {
        o.location = unpackPos(r.u64_());
        o.byte1 = r.u8_();
        o.byte2 = r.u8_();
        o.blockId = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct BlockBreakAnimation {
    static ids::PlayCb packetId() { return ids::PlayCb::BlockBreakAnimation; }
    i32 entityId;
    BlockPos location;
    i8 destroyStage;
};

static const u8 kVar_BlockBreakAnimation[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, BlockBreakAnimation& o, Version v) {
    o = BlockBreakAnimation();
    switch (kVar_BlockBreakAnimation[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.location = unpackPos(r.u64_());
        o.destroyStage = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct BlockChange {
    static ids::PlayCb packetId() { return ids::PlayCb::BlockChange; }
    BlockPos location;
    i32 type;
};

static const u8 kVar_BlockChange[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, BlockChange& o, Version v) {
    o = BlockChange();
    switch (kVar_BlockChange[(int)v]) {
    case 0: {
        o.location = unpackPos(r.u64_());
        o.type = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct BossBar {
    static ids::PlayCb packetId() { return ids::PlayCb::BossBar; }
    Uuid entityUUID;
    i32 action;
    StrView title;
    float health;
    i32 color;
    i32 dividers;
    u8 flags;
};

static const u8 kVar_BossBar[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, BossBar& o, Version v) {
    o = BossBar();
    switch (kVar_BossBar[(int)v]) {
    case 0: {
        { const u8* p = r.bytes(16); if (p) memcpy(o.entityUUID.b, p, 16); }
        o.action = r.varint();
        if (o.action == 0 || o.action == 3) {
            o.title = r.str();
        }
        if (o.action == 0 || o.action == 2) {
            o.health = r.f32_();
        }
        if (o.action == 0 || o.action == 4) {
            o.color = r.varint();
        }
        if (o.action == 0 || o.action == 4) {
            o.dividers = r.varint();
        }
        if (o.action == 0 || o.action == 5) {
            o.flags = r.u8_();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct Camera {
    static ids::PlayCb packetId() { return ids::PlayCb::Camera; }
    i32 cameraId;
};

static const u8 kVar_Camera[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Camera& o, Version v) {
    o = Camera();
    switch (kVar_Camera[(int)v]) {
    case 0: {
        o.cameraId = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Chat {
    static ids::PlayCb packetId() { return ids::PlayCb::Chat; }
    StrView message;
    i8 position;
};

static const u8 kVar_Chat[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Chat& o, Version v) {
    o = Chat();
    switch (kVar_Chat[(int)v]) {
    case 0: {
        o.message = r.str();
        o.position = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct CloseWindow {
    static ids::PlayCb packetId() { return ids::PlayCb::CloseWindow; }
    u8 windowId;
};

static const u8 kVar_CloseWindow[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, CloseWindow& o, Version v) {
    o = CloseWindow();
    switch (kVar_CloseWindow[(int)v]) {
    case 0: {
        o.windowId = r.u8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Collect {
    static ids::PlayCb packetId() { return ids::PlayCb::Collect; }
    i32 collectedEntityId;
    i32 collectorEntityId;
    i32 pickupItemCount;
};

static const u8 kVar_Collect[6] = {0,1,1,1,1,1};
inline bool decode(Reader& r, Collect& o, Version v) {
    o = Collect();
    switch (kVar_Collect[(int)v]) {
    case 0: {
        o.collectedEntityId = r.varint();
        o.collectorEntityId = r.varint();
        break; }
    case 1: {
        o.collectedEntityId = r.varint();
        o.collectorEntityId = r.varint();
        o.pickupItemCount = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct CombatEvent {
    static ids::PlayCb packetId() { return ids::PlayCb::CombatEvent; }
    i32 event;
    i32 duration;
    i32 playerId;
    i32 entityId;
    StrView message;
};

static const u8 kVar_CombatEvent[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, CombatEvent& o, Version v) {
    o = CombatEvent();
    switch (kVar_CombatEvent[(int)v]) {
    case 0: {
        o.event = r.varint();
        if (o.event == 1) {
            o.duration = r.varint();
        }
        if (o.event == 2) {
            o.playerId = r.varint();
        }
        if (o.event == 1 || o.event == 2) {
            o.entityId = r.i32_();
        }
        if (o.event == 2) {
            o.message = r.str();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct CraftProgressBar {
    static ids::PlayCb packetId() { return ids::PlayCb::CraftProgressBar; }
    u8 windowId;
    i16 property;
    i16 value;
};

static const u8 kVar_CraftProgressBar[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, CraftProgressBar& o, Version v) {
    o = CraftProgressBar();
    switch (kVar_CraftProgressBar[(int)v]) {
    case 0: {
        o.windowId = r.u8_();
        o.property = r.i16_();
        o.value = r.i16_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct CraftRecipeResponse {
    static ids::PlayCb packetId() { return ids::PlayCb::CraftRecipeResponse; }
    i8 windowId;
    i32 recipe;
};

static const u8 kVar_CraftRecipeResponse[6] = {255,255,255,255,0,0};
inline bool decode(Reader& r, CraftRecipeResponse& o, Version v) {
    o = CraftRecipeResponse();
    switch (kVar_CraftRecipeResponse[(int)v]) {
    case 0: {
        o.windowId = r.i8_();
        o.recipe = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct CustomPayload {
    static ids::PlayCb packetId() { return ids::PlayCb::CustomPayload; }
    StrView channel;
    Bytes data;
};

static const u8 kVar_CustomPayload[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, CustomPayload& o, Version v) {
    o = CustomPayload();
    switch (kVar_CustomPayload[(int)v]) {
    case 0: {
        o.channel = r.str();
        { o.data.len = (u32)r.left(); o.data.data = r.bytes(r.left()); }
        break; }
    default: return false;
    }
    return r.ok();
}

struct Difficulty {
    static ids::PlayCb packetId() { return ids::PlayCb::Difficulty; }
    u8 difficulty;
};

static const u8 kVar_Difficulty[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Difficulty& o, Version v) {
    o = Difficulty();
    switch (kVar_Difficulty[(int)v]) {
    case 0: {
        o.difficulty = r.u8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Entity {
    static ids::PlayCb packetId() { return ids::PlayCb::Entity; }
    i32 entityId;
};

static const u8 kVar_Entity[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Entity& o, Version v) {
    o = Entity();
    switch (kVar_Entity[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityDestroy {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityDestroy; }
    Array<VarInt> entityIds;
};

static const u8 kVar_EntityDestroy[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityDestroy& o, Version v) {
    o = EntityDestroy();
    switch (kVar_EntityDestroy[(int)v]) {
    case 0: {
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.entityIds.r = r; o.entityIds.r.err = false; o.entityIds.n = (u32)n; o.entityIds.v = v; o.entityIds.ctx = 0;
            VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.entityIds.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityEffect {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityEffect; }
    i32 entityId;
    i8 effectId;
    i8 amplifier;
    i32 duration;
    i8 hideParticles;
};

static const u8 kVar_EntityEffect[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityEffect& o, Version v) {
    o = EntityEffect();
    switch (kVar_EntityEffect[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.effectId = r.i8_();
        o.amplifier = r.i8_();
        o.duration = r.varint();
        o.hideParticles = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityEquipment {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityEquipment; }
    i32 entityId;
    i32 slot;
    Slot item;
};

static const u8 kVar_EntityEquipment[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityEquipment& o, Version v) {
    o = EntityEquipment();
    switch (kVar_EntityEquipment[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.slot = r.varint();
        if (!decodeSlot(r, o.item)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityHeadRotation {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityHeadRotation; }
    i32 entityId;
    i8 headYaw;
};

static const u8 kVar_EntityHeadRotation[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityHeadRotation& o, Version v) {
    o = EntityHeadRotation();
    switch (kVar_EntityHeadRotation[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.headYaw = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityLook {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityLook; }
    i32 entityId;
    i8 yaw;
    i8 pitch;
    bool onGround;
};

static const u8 kVar_EntityLook[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityLook& o, Version v) {
    o = EntityLook();
    switch (kVar_EntityLook[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        o.onGround = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityMetadata {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityMetadata; }
    i32 entityId;
    MetaView metadata;
};

static const u8 kVar_EntityMetadata[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityMetadata& o, Version v) {
    o = EntityMetadata();
    switch (kVar_EntityMetadata[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        if (!decodeMeta(r, o.metadata, v)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityMoveLook {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityMoveLook; }
    i32 entityId;
    i16 dX;
    i16 dY;
    i16 dZ;
    i8 yaw;
    i8 pitch;
    bool onGround;
};

static const u8 kVar_EntityMoveLook[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityMoveLook& o, Version v) {
    o = EntityMoveLook();
    switch (kVar_EntityMoveLook[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.dX = r.i16_();
        o.dY = r.i16_();
        o.dZ = r.i16_();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        o.onGround = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityStatus {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityStatus; }
    i32 entityId;
    i8 entityStatus;
};

static const u8 kVar_EntityStatus[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityStatus& o, Version v) {
    o = EntityStatus();
    switch (kVar_EntityStatus[(int)v]) {
    case 0: {
        o.entityId = r.i32_();
        o.entityStatus = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityTeleport {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityTeleport; }
    i32 entityId;
    double x;
    double y;
    double z;
    i8 yaw;
    i8 pitch;
    bool onGround;
};

static const u8 kVar_EntityTeleport[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityTeleport& o, Version v) {
    o = EntityTeleport();
    switch (kVar_EntityTeleport[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        o.onGround = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityUpdateAttributes_properties_modifiers {
    Uuid uuid;
    double amount;
    i8 operation;
};

struct EntityUpdateAttributes_properties {
    StrView key;
    double value;
    Array<EntityUpdateAttributes_properties_modifiers> modifiers;
};

inline bool decodeElem(Reader& r, EntityUpdateAttributes_properties_modifiers& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = EntityUpdateAttributes_properties_modifiers();
    { const u8* p = r.bytes(16); if (p) memcpy(o.uuid.b, p, 16); }
    o.amount = r.f64_();
    o.operation = r.i8_();
    return r.ok();
}

inline bool decodeElem(Reader& r, EntityUpdateAttributes_properties& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = EntityUpdateAttributes_properties();
    o.key = r.str();
    o.value = r.f64_();
    { i32 n = r.varint();
        if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
        o.modifiers.r = r; o.modifiers.r.err = false; o.modifiers.n = (u32)n; o.modifiers.v = v; o.modifiers.ctx = 0;
        EntityUpdateAttributes_properties_modifiers tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
        o.modifiers.r.end = r.p; }
    return r.ok();
}

struct EntityUpdateAttributes {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityUpdateAttributes; }
    i32 entityId;
    Array<EntityUpdateAttributes_properties> properties;
};

static const u8 kVar_EntityUpdateAttributes[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityUpdateAttributes& o, Version v) {
    o = EntityUpdateAttributes();
    switch (kVar_EntityUpdateAttributes[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { i32 n = r.i32_();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.properties.r = r; o.properties.r.err = false; o.properties.n = (u32)n; o.properties.v = v; o.properties.ctx = 0;
            EntityUpdateAttributes_properties tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.properties.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct EntityVelocity_velocity {
    i16 x;
    i16 y;
    i16 z;
};

inline bool decodeElem(Reader& r, EntityVelocity_velocity& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = EntityVelocity_velocity();
    o.x = r.i16_();
    o.y = r.i16_();
    o.z = r.i16_();
    return r.ok();
}

struct EntityVelocity {
    static ids::PlayCb packetId() { return ids::PlayCb::EntityVelocity; }
    i32 entityId;
    EntityVelocity_velocity velocity;
};

static const u8 kVar_EntityVelocity[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, EntityVelocity& o, Version v) {
    o = EntityVelocity();
    switch (kVar_EntityVelocity[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        if (!decodeElem(r, o.velocity, v, 0)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct Experience {
    static ids::PlayCb packetId() { return ids::PlayCb::Experience; }
    float experienceBar;
    i32 level;
    i32 totalExperience;
};

static const u8 kVar_Experience[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Experience& o, Version v) {
    o = Experience();
    switch (kVar_Experience[(int)v]) {
    case 0: {
        o.experienceBar = r.f32_();
        o.level = r.varint();
        o.totalExperience = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Explosion_affectedBlockOffsets {
    i8 x;
    i8 y;
    i8 z;
};

inline bool decodeElem(Reader& r, Explosion_affectedBlockOffsets& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Explosion_affectedBlockOffsets();
    o.x = r.i8_();
    o.y = r.i8_();
    o.z = r.i8_();
    return r.ok();
}

struct Explosion {
    static ids::PlayCb packetId() { return ids::PlayCb::Explosion; }
    float x;
    float y;
    float z;
    float radius;
    Array<Explosion_affectedBlockOffsets> affectedBlockOffsets;
    float playerMotionX;
    float playerMotionY;
    float playerMotionZ;
};

static const u8 kVar_Explosion[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Explosion& o, Version v) {
    o = Explosion();
    switch (kVar_Explosion[(int)v]) {
    case 0: {
        o.x = r.f32_();
        o.y = r.f32_();
        o.z = r.f32_();
        o.radius = r.f32_();
        { i32 n = r.i32_();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.affectedBlockOffsets.r = r; o.affectedBlockOffsets.r.err = false; o.affectedBlockOffsets.n = (u32)n; o.affectedBlockOffsets.v = v; o.affectedBlockOffsets.ctx = 0;
            Explosion_affectedBlockOffsets tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.affectedBlockOffsets.r.end = r.p; }
        o.playerMotionX = r.f32_();
        o.playerMotionY = r.f32_();
        o.playerMotionZ = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct GameStateChange {
    static ids::PlayCb packetId() { return ids::PlayCb::GameStateChange; }
    u8 reason;
    float gameMode;
};

static const u8 kVar_GameStateChange[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, GameStateChange& o, Version v) {
    o = GameStateChange();
    switch (kVar_GameStateChange[(int)v]) {
    case 0: {
        o.reason = r.u8_();
        o.gameMode = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct HeldItemSlot {
    static ids::PlayCb packetId() { return ids::PlayCb::HeldItemSlot; }
    i8 slot;
};

static const u8 kVar_HeldItemSlot[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, HeldItemSlot& o, Version v) {
    o = HeldItemSlot();
    switch (kVar_HeldItemSlot[(int)v]) {
    case 0: {
        o.slot = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct KeepAlive {
    static ids::PlayCb packetId() { return ids::PlayCb::KeepAlive; }
    i64 keepAliveId;
};

static const u8 kVar_KeepAlive[6] = {0,0,0,0,0,1};
inline bool decode(Reader& r, KeepAlive& o, Version v) {
    o = KeepAlive();
    switch (kVar_KeepAlive[(int)v]) {
    case 0: {
        o.keepAliveId = r.varint();
        break; }
    case 1: {
        o.keepAliveId = r.i64_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct KickDisconnect {
    static ids::PlayCb packetId() { return ids::PlayCb::KickDisconnect; }
    StrView reason;
};

static const u8 kVar_KickDisconnect[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, KickDisconnect& o, Version v) {
    o = KickDisconnect();
    switch (kVar_KickDisconnect[(int)v]) {
    case 0: {
        o.reason = r.str();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Login {
    static ids::PlayCb packetId() { return ids::PlayCb::Login; }
    i32 entityId;
    u8 gameMode;
    i32 dimension;
    u8 difficulty;
    u8 maxPlayers;
    StrView levelType;
    bool reducedDebugInfo;
};

static const u8 kVar_Login[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Login& o, Version v) {
    o = Login();
    switch (kVar_Login[(int)v]) {
    case 0: {
        o.entityId = r.i32_();
        o.gameMode = r.u8_();
        o.dimension = r.i32_();
        o.difficulty = r.u8_();
        o.maxPlayers = r.u8_();
        o.levelType = r.str();
        o.reducedDebugInfo = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Map_icons {
    i8 directionAndType;
    i8 x;
    i8 z;
};

inline bool decodeElem(Reader& r, Map_icons& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Map_icons();
    o.directionAndType = r.i8_();
    o.x = r.i8_();
    o.z = r.i8_();
    return r.ok();
}

struct Map {
    static ids::PlayCb packetId() { return ids::PlayCb::Map; }
    i32 itemDamage;
    i8 scale;
    bool trackingPosition;
    Array<Map_icons> icons;
    i8 columns;
    i8 rows;
    i8 x;
    i8 y;
    Bytes data;
};

static const u8 kVar_Map[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Map& o, Version v) {
    o = Map();
    switch (kVar_Map[(int)v]) {
    case 0: {
        o.itemDamage = r.varint();
        o.scale = r.i8_();
        o.trackingPosition = r.bool_();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.icons.r = r; o.icons.r.err = false; o.icons.n = (u32)n; o.icons.v = v; o.icons.ctx = 0;
            Map_icons tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.icons.r.end = r.p; }
        o.columns = r.i8_();
        if (!(o.columns == 0)) {
            o.rows = r.i8_();
        }
        if (!(o.columns == 0)) {
            o.x = r.i8_();
        }
        if (!(o.columns == 0)) {
            o.y = r.i8_();
        }
        if (!(o.columns == 0)) {
            { i32 n = r.varint(); if (!r.ok() || n < 0) return false; o.data.data = r.bytes((size_t)n); o.data.len = (u32)n; }
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct MapChunk {
    static ids::PlayCb packetId() { return ids::PlayCb::MapChunk; }
    i32 x;
    i32 z;
    bool groundUp;
    i32 bitMap;
    Bytes chunkData;
    Array<Bytes> blockEntities;
};

static const u8 kVar_MapChunk[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, MapChunk& o, Version v) {
    o = MapChunk();
    switch (kVar_MapChunk[(int)v]) {
    case 0: {
        o.x = r.i32_();
        o.z = r.i32_();
        o.groundUp = r.bool_();
        o.bitMap = r.varint();
        { i32 n = r.varint(); if (!r.ok() || n < 0) return false; o.chunkData.data = r.bytes((size_t)n); o.chunkData.len = (u32)n; }
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.blockEntities.r = r; o.blockEntities.r.err = false; o.blockEntities.n = (u32)n; o.blockEntities.v = v; o.blockEntities.ctx = 0;
            Bytes tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.blockEntities.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct MultiBlockChange_records {
    u8 horizontalPos;
    u8 y;
    i32 blockId;
};

inline bool decodeElem(Reader& r, MultiBlockChange_records& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = MultiBlockChange_records();
    o.horizontalPos = r.u8_();
    o.y = r.u8_();
    o.blockId = r.varint();
    return r.ok();
}

struct MultiBlockChange {
    static ids::PlayCb packetId() { return ids::PlayCb::MultiBlockChange; }
    i32 chunkX;
    i32 chunkZ;
    Array<MultiBlockChange_records> records;
};

static const u8 kVar_MultiBlockChange[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, MultiBlockChange& o, Version v) {
    o = MultiBlockChange();
    switch (kVar_MultiBlockChange[(int)v]) {
    case 0: {
        o.chunkX = r.i32_();
        o.chunkZ = r.i32_();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.records.r = r; o.records.r.err = false; o.records.n = (u32)n; o.records.v = v; o.records.ctx = 0;
            MultiBlockChange_records tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.records.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct NamedEntitySpawn {
    static ids::PlayCb packetId() { return ids::PlayCb::NamedEntitySpawn; }
    i32 entityId;
    Uuid playerUUID;
    double x;
    double y;
    double z;
    i8 yaw;
    i8 pitch;
    MetaView metadata;
};

static const u8 kVar_NamedEntitySpawn[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, NamedEntitySpawn& o, Version v) {
    o = NamedEntitySpawn();
    switch (kVar_NamedEntitySpawn[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { const u8* p = r.bytes(16); if (p) memcpy(o.playerUUID.b, p, 16); }
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        if (!decodeMeta(r, o.metadata, v)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct NamedSoundEffect {
    static ids::PlayCb packetId() { return ids::PlayCb::NamedSoundEffect; }
    StrView soundName;
    i32 soundCategory;
    i32 x;
    i32 y;
    i32 z;
    float volume;
    float pitch;
};

static const u8 kVar_NamedSoundEffect[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, NamedSoundEffect& o, Version v) {
    o = NamedSoundEffect();
    switch (kVar_NamedSoundEffect[(int)v]) {
    case 0: {
        o.soundName = r.str();
        o.soundCategory = r.varint();
        o.x = r.i32_();
        o.y = r.i32_();
        o.z = r.i32_();
        o.volume = r.f32_();
        o.pitch = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct OpenSignEntity {
    static ids::PlayCb packetId() { return ids::PlayCb::OpenSignEntity; }
    BlockPos location;
};

static const u8 kVar_OpenSignEntity[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, OpenSignEntity& o, Version v) {
    o = OpenSignEntity();
    switch (kVar_OpenSignEntity[(int)v]) {
    case 0: {
        o.location = unpackPos(r.u64_());
        break; }
    default: return false;
    }
    return r.ok();
}

struct OpenWindow {
    static ids::PlayCb packetId() { return ids::PlayCb::OpenWindow; }
    u8 windowId;
    StrView inventoryType;
    StrView windowTitle;
    u8 slotCount;
    i32 entityId;
};

static const u8 kVar_OpenWindow[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, OpenWindow& o, Version v) {
    o = OpenWindow();
    switch (kVar_OpenWindow[(int)v]) {
    case 0: {
        o.windowId = r.u8_();
        o.inventoryType = r.str();
        o.windowTitle = r.str();
        o.slotCount = r.u8_();
        if (streq(o.inventoryType, "EntityHorse")) {
            o.entityId = r.i32_();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct PlayerInfo_data_properties {
    StrView name;
    StrView value;
    Opt<StrView> signature;
};

struct PlayerInfo_data {
    Uuid uuid;
    StrView name;
    Array<PlayerInfo_data_properties> properties;
    i32 gamemode;
    i32 ping;
    Opt<StrView> displayName;
};

inline bool decodeElem(Reader& r, PlayerInfo_data_properties& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = PlayerInfo_data_properties();
    o.name = r.str();
    o.value = r.str();
    o.signature.has = r.bool_();
    if (o.signature.has) {
        o.signature.v = r.str();
    }
    return r.ok();
}

inline bool decodeElem(Reader& r, PlayerInfo_data& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = PlayerInfo_data();
    { const u8* p = r.bytes(16); if (p) memcpy(o.uuid.b, p, 16); }
    if (ctx == 0) {
        o.name = r.str();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.properties.r = r; o.properties.r.err = false; o.properties.n = (u32)n; o.properties.v = v; o.properties.ctx = 0;
            PlayerInfo_data_properties tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.properties.r.end = r.p; }
        o.gamemode = r.varint();
        o.ping = r.varint();
        o.displayName.has = r.bool_();
        if (o.displayName.has) {
            o.displayName.v = r.str();
        }
    }
    if (ctx == 3) {
        o.displayName.has = r.bool_();
        if (o.displayName.has) {
            o.displayName.v = r.str();
        }
    }
    if (ctx == 1) {
        o.gamemode = r.varint();
    }
    if (ctx == 2) {
        o.ping = r.varint();
    }
    return r.ok();
}

struct PlayerInfo {
    static ids::PlayCb packetId() { return ids::PlayCb::PlayerInfo; }
    i32 action;
    Array<PlayerInfo_data> data;
};

static const u8 kVar_PlayerInfo[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, PlayerInfo& o, Version v) {
    o = PlayerInfo();
    switch (kVar_PlayerInfo[(int)v]) {
    case 0: {
        o.action = r.varint();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.data.r = r; o.data.r.err = false; o.data.n = (u32)n; o.data.v = v; o.data.ctx = (i32)o.action;
            PlayerInfo_data tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, (i32)o.action)) return false;
            o.data.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct PlayerlistHeader {
    static ids::PlayCb packetId() { return ids::PlayCb::PlayerlistHeader; }
    StrView header;
    StrView footer;
};

static const u8 kVar_PlayerlistHeader[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, PlayerlistHeader& o, Version v) {
    o = PlayerlistHeader();
    switch (kVar_PlayerlistHeader[(int)v]) {
    case 0: {
        o.header = r.str();
        o.footer = r.str();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Position {
    static ids::PlayCb packetId() { return ids::PlayCb::Position; }
    double x;
    double y;
    double z;
    float yaw;
    float pitch;
    i8 flags;
    i32 teleportId;
};

static const u8 kVar_Position[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Position& o, Version v) {
    o = Position();
    switch (kVar_Position[(int)v]) {
    case 0: {
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.f32_();
        o.pitch = r.f32_();
        o.flags = r.i8_();
        o.teleportId = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct RelEntityMove {
    static ids::PlayCb packetId() { return ids::PlayCb::RelEntityMove; }
    i32 entityId;
    i16 dX;
    i16 dY;
    i16 dZ;
    bool onGround;
};

static const u8 kVar_RelEntityMove[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, RelEntityMove& o, Version v) {
    o = RelEntityMove();
    switch (kVar_RelEntityMove[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.dX = r.i16_();
        o.dY = r.i16_();
        o.dZ = r.i16_();
        o.onGround = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct RemoveEntityEffect {
    static ids::PlayCb packetId() { return ids::PlayCb::RemoveEntityEffect; }
    i32 entityId;
    i8 effectId;
};

static const u8 kVar_RemoveEntityEffect[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, RemoveEntityEffect& o, Version v) {
    o = RemoveEntityEffect();
    switch (kVar_RemoveEntityEffect[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.effectId = r.i8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct ResourcePackSend {
    static ids::PlayCb packetId() { return ids::PlayCb::ResourcePackSend; }
    StrView url;
    StrView hash;
};

static const u8 kVar_ResourcePackSend[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, ResourcePackSend& o, Version v) {
    o = ResourcePackSend();
    switch (kVar_ResourcePackSend[(int)v]) {
    case 0: {
        o.url = r.str();
        o.hash = r.str();
        break; }
    default: return false;
    }
    return r.ok();
}

struct Respawn {
    static ids::PlayCb packetId() { return ids::PlayCb::Respawn; }
    i32 dimension;
    u8 difficulty;
    u8 gamemode;
    StrView levelType;
};

static const u8 kVar_Respawn[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Respawn& o, Version v) {
    o = Respawn();
    switch (kVar_Respawn[(int)v]) {
    case 0: {
        o.dimension = r.i32_();
        o.difficulty = r.u8_();
        o.gamemode = r.u8_();
        o.levelType = r.str();
        break; }
    default: return false;
    }
    return r.ok();
}

struct ScoreboardDisplayObjective {
    static ids::PlayCb packetId() { return ids::PlayCb::ScoreboardDisplayObjective; }
    i8 position;
    StrView name;
};

static const u8 kVar_ScoreboardDisplayObjective[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, ScoreboardDisplayObjective& o, Version v) {
    o = ScoreboardDisplayObjective();
    switch (kVar_ScoreboardDisplayObjective[(int)v]) {
    case 0: {
        o.position = r.i8_();
        o.name = r.str();
        break; }
    default: return false;
    }
    return r.ok();
}

struct ScoreboardObjective {
    static ids::PlayCb packetId() { return ids::PlayCb::ScoreboardObjective; }
    StrView name;
    i8 action;
    StrView displayText;
    StrView type;
};

static const u8 kVar_ScoreboardObjective[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, ScoreboardObjective& o, Version v) {
    o = ScoreboardObjective();
    switch (kVar_ScoreboardObjective[(int)v]) {
    case 0: {
        o.name = r.str();
        o.action = r.i8_();
        if (o.action == 0 || o.action == 2) {
            o.displayText = r.str();
        }
        if (o.action == 0 || o.action == 2) {
            o.type = r.str();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct ScoreboardScore {
    static ids::PlayCb packetId() { return ids::PlayCb::ScoreboardScore; }
    StrView itemName;
    i32 action;
    StrView scoreName;
    i32 value;
};

static const u8 kVar_ScoreboardScore[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, ScoreboardScore& o, Version v) {
    o = ScoreboardScore();
    switch (kVar_ScoreboardScore[(int)v]) {
    case 0: {
        o.itemName = r.str();
        o.action = r.varint();
        o.scoreName = r.str();
        if (!(o.action == 1)) {
            o.value = r.varint();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct SelectAdvancementTab {
    static ids::PlayCb packetId() { return ids::PlayCb::SelectAdvancementTab; }
    Opt<StrView> id;
};

static const u8 kVar_SelectAdvancementTab[6] = {255,255,255,0,0,0};
inline bool decode(Reader& r, SelectAdvancementTab& o, Version v) {
    o = SelectAdvancementTab();
    switch (kVar_SelectAdvancementTab[(int)v]) {
    case 0: {
        o.id.has = r.bool_();
        if (o.id.has) {
            o.id.v = r.str();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct SetCooldown {
    static ids::PlayCb packetId() { return ids::PlayCb::SetCooldown; }
    i32 itemID;
    i32 cooldownTicks;
};

static const u8 kVar_SetCooldown[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SetCooldown& o, Version v) {
    o = SetCooldown();
    switch (kVar_SetCooldown[(int)v]) {
    case 0: {
        o.itemID = r.varint();
        o.cooldownTicks = r.varint();
        break; }
    default: return false;
    }
    return r.ok();
}

struct SetPassengers {
    static ids::PlayCb packetId() { return ids::PlayCb::SetPassengers; }
    i32 entityId;
    Array<VarInt> passengers;
};

static const u8 kVar_SetPassengers[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SetPassengers& o, Version v) {
    o = SetPassengers();
    switch (kVar_SetPassengers[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.passengers.r = r; o.passengers.r.err = false; o.passengers.n = (u32)n; o.passengers.v = v; o.passengers.ctx = 0;
            VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.passengers.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct SetSlot {
    static ids::PlayCb packetId() { return ids::PlayCb::SetSlot; }
    i8 windowId;
    i16 slot;
    Slot item;
};

static const u8 kVar_SetSlot[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SetSlot& o, Version v) {
    o = SetSlot();
    switch (kVar_SetSlot[(int)v]) {
    case 0: {
        o.windowId = r.i8_();
        o.slot = r.i16_();
        if (!decodeSlot(r, o.item)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct SoundEffect {
    static ids::PlayCb packetId() { return ids::PlayCb::SoundEffect; }
    i32 soundId;
    i32 soundCategory;
    i32 x;
    i32 y;
    i32 z;
    float volume;
    float pitch;
};

static const u8 kVar_SoundEffect[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SoundEffect& o, Version v) {
    o = SoundEffect();
    switch (kVar_SoundEffect[(int)v]) {
    case 0: {
        o.soundId = r.varint();
        o.soundCategory = r.varint();
        o.x = r.i32_();
        o.y = r.i32_();
        o.z = r.i32_();
        o.volume = r.f32_();
        o.pitch = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnEntity_velocity {
    i16 x;
    i16 y;
    i16 z;
};

inline bool decodeElem(Reader& r, SpawnEntity_velocity& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = SpawnEntity_velocity();
    o.x = r.i16_();
    o.y = r.i16_();
    o.z = r.i16_();
    return r.ok();
}

struct SpawnEntity {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnEntity; }
    i32 entityId;
    Uuid objectUUID;
    i8 type;
    double x;
    double y;
    double z;
    i8 pitch;
    i8 yaw;
    i32 objectData;
    SpawnEntity_velocity velocity;
};

static const u8 kVar_SpawnEntity[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SpawnEntity& o, Version v) {
    o = SpawnEntity();
    switch (kVar_SpawnEntity[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { const u8* p = r.bytes(16); if (p) memcpy(o.objectUUID.b, p, 16); }
        o.type = r.i8_();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.pitch = r.i8_();
        o.yaw = r.i8_();
        o.objectData = r.i32_();
        if (!decodeElem(r, o.velocity, v, 0)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnEntityExperienceOrb {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnEntityExperienceOrb; }
    i32 entityId;
    double x;
    double y;
    double z;
    i16 count;
};

static const u8 kVar_SpawnEntityExperienceOrb[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SpawnEntityExperienceOrb& o, Version v) {
    o = SpawnEntityExperienceOrb();
    switch (kVar_SpawnEntityExperienceOrb[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.count = r.i16_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnEntityLiving_velocity {
    i16 x;
    i16 y;
    i16 z;
};

inline bool decodeElem(Reader& r, SpawnEntityLiving_velocity& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = SpawnEntityLiving_velocity();
    o.x = r.i16_();
    o.y = r.i16_();
    o.z = r.i16_();
    return r.ok();
}

struct SpawnEntityLiving {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnEntityLiving; }
    i32 entityId;
    Uuid entityUUID;
    i32 type;
    double x;
    double y;
    double z;
    i8 yaw;
    i8 pitch;
    i8 headPitch;
    SpawnEntityLiving_velocity velocity;
    MetaView metadata;
};

static const u8 kVar_SpawnEntityLiving[6] = {0,1,1,1,1,1};
inline bool decode(Reader& r, SpawnEntityLiving& o, Version v) {
    o = SpawnEntityLiving();
    switch (kVar_SpawnEntityLiving[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { const u8* p = r.bytes(16); if (p) memcpy(o.entityUUID.b, p, 16); }
        o.type = r.u8_();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        o.headPitch = r.i8_();
        if (!decodeElem(r, o.velocity, v, 0)) return false;
        if (!decodeMeta(r, o.metadata, v)) return false;
        break; }
    case 1: {
        o.entityId = r.varint();
        { const u8* p = r.bytes(16); if (p) memcpy(o.entityUUID.b, p, 16); }
        o.type = r.varint();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.i8_();
        o.pitch = r.i8_();
        o.headPitch = r.i8_();
        if (!decodeElem(r, o.velocity, v, 0)) return false;
        if (!decodeMeta(r, o.metadata, v)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnEntityPainting {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnEntityPainting; }
    i32 entityId;
    Uuid entityUUID;
    StrView title;
    BlockPos location;
    u8 direction;
};

static const u8 kVar_SpawnEntityPainting[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SpawnEntityPainting& o, Version v) {
    o = SpawnEntityPainting();
    switch (kVar_SpawnEntityPainting[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        { const u8* p = r.bytes(16); if (p) memcpy(o.entityUUID.b, p, 16); }
        o.title = r.str();
        o.location = unpackPos(r.u64_());
        o.direction = r.u8_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnEntityWeather {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnEntityWeather; }
    i32 entityId;
    i8 type;
    double x;
    double y;
    double z;
};

static const u8 kVar_SpawnEntityWeather[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SpawnEntityWeather& o, Version v) {
    o = SpawnEntityWeather();
    switch (kVar_SpawnEntityWeather[(int)v]) {
    case 0: {
        o.entityId = r.varint();
        o.type = r.i8_();
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct SpawnPosition {
    static ids::PlayCb packetId() { return ids::PlayCb::SpawnPosition; }
    BlockPos location;
};

static const u8 kVar_SpawnPosition[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, SpawnPosition& o, Version v) {
    o = SpawnPosition();
    switch (kVar_SpawnPosition[(int)v]) {
    case 0: {
        o.location = unpackPos(r.u64_());
        break; }
    default: return false;
    }
    return r.ok();
}

struct Statistics_entries {
    StrView name;
    i32 value;
};

inline bool decodeElem(Reader& r, Statistics_entries& o, Version v, i32 ctx) {
    (void)v; (void)ctx; o = Statistics_entries();
    o.name = r.str();
    o.value = r.varint();
    return r.ok();
}

struct Statistics {
    static ids::PlayCb packetId() { return ids::PlayCb::Statistics; }
    Array<Statistics_entries> entries;
};

static const u8 kVar_Statistics[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Statistics& o, Version v) {
    o = Statistics();
    switch (kVar_Statistics[(int)v]) {
    case 0: {
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.entries.r = r; o.entries.r.err = false; o.entries.n = (u32)n; o.entries.v = v; o.entries.ctx = 0;
            Statistics_entries tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.entries.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct TabComplete {
    static ids::PlayCb packetId() { return ids::PlayCb::TabComplete; }
    Array<StrView> matches;
};

static const u8 kVar_TabComplete[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, TabComplete& o, Version v) {
    o = TabComplete();
    switch (kVar_TabComplete[(int)v]) {
    case 0: {
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.matches.r = r; o.matches.r.err = false; o.matches.n = (u32)n; o.matches.v = v; o.matches.ctx = 0;
            StrView tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.matches.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct Teams {
    static ids::PlayCb packetId() { return ids::PlayCb::Teams; }
    StrView team;
    i8 mode;
    StrView name;
    StrView prefix;
    StrView suffix;
    i8 friendlyFire;
    StrView nameTagVisibility;
    StrView collisionRule;
    i8 color;
    Array<StrView> players;
};

static const u8 kVar_Teams[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Teams& o, Version v) {
    o = Teams();
    switch (kVar_Teams[(int)v]) {
    case 0: {
        o.team = r.str();
        o.mode = r.i8_();
        if (o.mode == 0 || o.mode == 2) {
            o.name = r.str();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.prefix = r.str();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.suffix = r.str();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.friendlyFire = r.i8_();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.nameTagVisibility = r.str();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.collisionRule = r.str();
        }
        if (o.mode == 0 || o.mode == 2) {
            o.color = r.i8_();
        }
        if (o.mode == 0 || o.mode == 3 || o.mode == 4) {
            { i32 n = r.varint();
                if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
                o.players.r = r; o.players.r.err = false; o.players.n = (u32)n; o.players.v = v; o.players.ctx = 0;
                StrView tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
                o.players.r.end = r.p; }
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct TileEntityData {
    static ids::PlayCb packetId() { return ids::PlayCb::TileEntityData; }
    BlockPos location;
    u8 action;
    Bytes nbtData;
};

static const u8 kVar_TileEntityData[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, TileEntityData& o, Version v) {
    o = TileEntityData();
    switch (kVar_TileEntityData[(int)v]) {
    case 0: {
        o.location = unpackPos(r.u64_());
        o.action = r.u8_();
        if (!readNbt(r, o.nbtData, true)) return false;
        break; }
    default: return false;
    }
    return r.ok();
}

struct Title {
    static ids::PlayCb packetId() { return ids::PlayCb::Title; }
    i32 action;
    StrView text;
    i32 fadeIn;
    i32 stay;
    i32 fadeOut;
};

static const u8 kVar_Title[6] = {0,1,1,1,1,1};
inline bool decode(Reader& r, Title& o, Version v) {
    o = Title();
    switch (kVar_Title[(int)v]) {
    case 0: {
        o.action = r.varint();
        if (o.action == 0 || o.action == 1) {
            o.text = r.str();
        }
        if (o.action == 2) {
            o.fadeIn = r.i32_();
        }
        if (o.action == 2) {
            o.stay = r.i32_();
        }
        if (o.action == 2) {
            o.fadeOut = r.i32_();
        }
        break; }
    case 1: {
        o.action = r.varint();
        if (o.action == 0 || o.action == 1 || o.action == 2) {
            o.text = r.str();
        }
        if (o.action == 3) {
            o.fadeIn = r.i32_();
        }
        if (o.action == 3) {
            o.stay = r.i32_();
        }
        if (o.action == 3) {
            o.fadeOut = r.i32_();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct Transaction {
    static ids::PlayCb packetId() { return ids::PlayCb::Transaction; }
    i8 windowId;
    i16 action;
    bool accepted;
};

static const u8 kVar_Transaction[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, Transaction& o, Version v) {
    o = Transaction();
    switch (kVar_Transaction[(int)v]) {
    case 0: {
        o.windowId = r.i8_();
        o.action = r.i16_();
        o.accepted = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct UnloadChunk {
    static ids::PlayCb packetId() { return ids::PlayCb::UnloadChunk; }
    i32 chunkX;
    i32 chunkZ;
};

static const u8 kVar_UnloadChunk[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, UnloadChunk& o, Version v) {
    o = UnloadChunk();
    switch (kVar_UnloadChunk[(int)v]) {
    case 0: {
        o.chunkX = r.i32_();
        o.chunkZ = r.i32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct UnlockRecipes {
    static ids::PlayCb packetId() { return ids::PlayCb::UnlockRecipes; }
    i32 action;
    bool craftingBookOpen;
    bool filteringCraftable;
    Array<VarInt> recipes1;
    Array<VarInt> recipes2;
};

static const u8 kVar_UnlockRecipes[6] = {255,255,255,0,0,0};
inline bool decode(Reader& r, UnlockRecipes& o, Version v) {
    o = UnlockRecipes();
    switch (kVar_UnlockRecipes[(int)v]) {
    case 0: {
        o.action = r.varint();
        o.craftingBookOpen = r.bool_();
        o.filteringCraftable = r.bool_();
        { i32 n = r.varint();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.recipes1.r = r; o.recipes1.r.err = false; o.recipes1.n = (u32)n; o.recipes1.v = v; o.recipes1.ctx = 0;
            VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.recipes1.r.end = r.p; }
        if (o.action == 0) {
            { i32 n = r.varint();
                if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
                o.recipes2.r = r; o.recipes2.r.err = false; o.recipes2.n = (u32)n; o.recipes2.v = v; o.recipes2.ctx = 0;
                VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
                o.recipes2.r.end = r.p; }
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct UpdateHealth {
    static ids::PlayCb packetId() { return ids::PlayCb::UpdateHealth; }
    float health;
    i32 food;
    float foodSaturation;
};

static const u8 kVar_UpdateHealth[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, UpdateHealth& o, Version v) {
    o = UpdateHealth();
    switch (kVar_UpdateHealth[(int)v]) {
    case 0: {
        o.health = r.f32_();
        o.food = r.varint();
        o.foodSaturation = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct UpdateTime {
    static ids::PlayCb packetId() { return ids::PlayCb::UpdateTime; }
    i64 age;
    i64 time;
};

static const u8 kVar_UpdateTime[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, UpdateTime& o, Version v) {
    o = UpdateTime();
    switch (kVar_UpdateTime[(int)v]) {
    case 0: {
        o.age = r.i64_();
        o.time = r.i64_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct VehicleMove {
    static ids::PlayCb packetId() { return ids::PlayCb::VehicleMove; }
    double x;
    double y;
    double z;
    float yaw;
    float pitch;
};

static const u8 kVar_VehicleMove[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, VehicleMove& o, Version v) {
    o = VehicleMove();
    switch (kVar_VehicleMove[(int)v]) {
    case 0: {
        o.x = r.f64_();
        o.y = r.f64_();
        o.z = r.f64_();
        o.yaw = r.f32_();
        o.pitch = r.f32_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct WindowItems {
    static ids::PlayCb packetId() { return ids::PlayCb::WindowItems; }
    u8 windowId;
    Array<Slot> items;
};

static const u8 kVar_WindowItems[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, WindowItems& o, Version v) {
    o = WindowItems();
    switch (kVar_WindowItems[(int)v]) {
    case 0: {
        o.windowId = r.u8_();
        { i32 n = r.i16_();
            if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
            o.items.r = r; o.items.r.err = false; o.items.n = (u32)n; o.items.v = v; o.items.ctx = 0;
            Slot tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
            o.items.r.end = r.p; }
        break; }
    default: return false;
    }
    return r.ok();
}

struct WorldBorder {
    static ids::PlayCb packetId() { return ids::PlayCb::WorldBorder; }
    i32 action;
    double radius;
    double x;
    double z;
    double old_radius;
    double new_radius;
    i64 speed;
    i32 portalBoundary;
    i32 warning_time;
    i32 warning_blocks;
};

static const u8 kVar_WorldBorder[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, WorldBorder& o, Version v) {
    o = WorldBorder();
    switch (kVar_WorldBorder[(int)v]) {
    case 0: {
        o.action = r.varint();
        if (o.action == 0) {
            o.radius = r.f64_();
        }
        if (o.action == 2 || o.action == 3) {
            o.x = r.f64_();
        }
        if (o.action == 2 || o.action == 3) {
            o.z = r.f64_();
        }
        if (o.action == 1 || o.action == 3) {
            o.old_radius = r.f64_();
        }
        if (o.action == 1 || o.action == 3) {
            o.new_radius = r.f64_();
        }
        if (o.action == 1 || o.action == 3) {
            o.speed = r.varlong();
        }
        if (o.action == 3) {
            o.portalBoundary = r.varint();
        }
        if (o.action == 3 || o.action == 4) {
            o.warning_time = r.varint();
        }
        if (o.action == 3 || o.action == 5) {
            o.warning_blocks = r.varint();
        }
        break; }
    default: return false;
    }
    return r.ok();
}

struct WorldEvent {
    static ids::PlayCb packetId() { return ids::PlayCb::WorldEvent; }
    i32 effectId;
    BlockPos location;
    i32 data;
    bool global;
};

static const u8 kVar_WorldEvent[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, WorldEvent& o, Version v) {
    o = WorldEvent();
    switch (kVar_WorldEvent[(int)v]) {
    case 0: {
        o.effectId = r.i32_();
        o.location = unpackPos(r.u64_());
        o.data = r.i32_();
        o.global = r.bool_();
        break; }
    default: return false;
    }
    return r.ok();
}

struct WorldParticles {
    static ids::PlayCb packetId() { return ids::PlayCb::WorldParticles; }
    i32 particleId;
    bool longDistance;
    float x;
    float y;
    float z;
    float offsetX;
    float offsetY;
    float offsetZ;
    float particleData;
    i32 particles;
    Array<VarInt> data;
};

static const u8 kVar_WorldParticles[6] = {0,0,0,0,0,0};
inline bool decode(Reader& r, WorldParticles& o, Version v) {
    o = WorldParticles();
    switch (kVar_WorldParticles[(int)v]) {
    case 0: {
        o.particleId = r.i32_();
        o.longDistance = r.bool_();
        o.x = r.f32_();
        o.y = r.f32_();
        o.z = r.f32_();
        o.offsetX = r.f32_();
        o.offsetY = r.f32_();
        o.offsetZ = r.f32_();
        o.particleData = r.f32_();
        o.particles = r.i32_();
        if (o.particleId == 36) {
            { i32 n = 2;
                if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
                o.data.r = r; o.data.r.err = false; o.data.n = (u32)n; o.data.v = v; o.data.ctx = 0;
                VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
                o.data.r.end = r.p; }
        }
        if (o.particleId == 37 || o.particleId == 38) {
            { i32 n = 1;
                if (!r.ok() || n < 0 || (size_t)n > r.left()) return false;
                o.data.r = r; o.data.r.err = false; o.data.n = (u32)n; o.data.v = v; o.data.ctx = 0;
                VarInt tmp; for (i32 j = 0; j < n; ++j) if (!decodeElem(r, tmp, v, 0)) return false;
                o.data.r.end = r.p; }
        }
        break; }
    default: return false;
    }
    return r.ok();
}

// Decodes (and discards) any clientbound packet by agnostic id - for validation/diagnostics.
inline bool validate(ids::PlayCb id, Reader r, Version v) {
    switch (id) {
    case ids::PlayCb::Abilities: { Abilities o; return decode(r, o, v); }
    case ids::PlayCb::Advancements: { Advancements o; return decode(r, o, v); }
    case ids::PlayCb::Animation: { Animation o; return decode(r, o, v); }
    case ids::PlayCb::AttachEntity: { AttachEntity o; return decode(r, o, v); }
    case ids::PlayCb::Bed: { Bed o; return decode(r, o, v); }
    case ids::PlayCb::BlockAction: { BlockAction o; return decode(r, o, v); }
    case ids::PlayCb::BlockBreakAnimation: { BlockBreakAnimation o; return decode(r, o, v); }
    case ids::PlayCb::BlockChange: { BlockChange o; return decode(r, o, v); }
    case ids::PlayCb::BossBar: { BossBar o; return decode(r, o, v); }
    case ids::PlayCb::Camera: { Camera o; return decode(r, o, v); }
    case ids::PlayCb::Chat: { Chat o; return decode(r, o, v); }
    case ids::PlayCb::CloseWindow: { CloseWindow o; return decode(r, o, v); }
    case ids::PlayCb::Collect: { Collect o; return decode(r, o, v); }
    case ids::PlayCb::CombatEvent: { CombatEvent o; return decode(r, o, v); }
    case ids::PlayCb::CraftProgressBar: { CraftProgressBar o; return decode(r, o, v); }
    case ids::PlayCb::CraftRecipeResponse: { CraftRecipeResponse o; return decode(r, o, v); }
    case ids::PlayCb::CustomPayload: { CustomPayload o; return decode(r, o, v); }
    case ids::PlayCb::Difficulty: { Difficulty o; return decode(r, o, v); }
    case ids::PlayCb::Entity: { Entity o; return decode(r, o, v); }
    case ids::PlayCb::EntityDestroy: { EntityDestroy o; return decode(r, o, v); }
    case ids::PlayCb::EntityEffect: { EntityEffect o; return decode(r, o, v); }
    case ids::PlayCb::EntityEquipment: { EntityEquipment o; return decode(r, o, v); }
    case ids::PlayCb::EntityHeadRotation: { EntityHeadRotation o; return decode(r, o, v); }
    case ids::PlayCb::EntityLook: { EntityLook o; return decode(r, o, v); }
    case ids::PlayCb::EntityMetadata: { EntityMetadata o; return decode(r, o, v); }
    case ids::PlayCb::EntityMoveLook: { EntityMoveLook o; return decode(r, o, v); }
    case ids::PlayCb::EntityStatus: { EntityStatus o; return decode(r, o, v); }
    case ids::PlayCb::EntityTeleport: { EntityTeleport o; return decode(r, o, v); }
    case ids::PlayCb::EntityUpdateAttributes: { EntityUpdateAttributes o; return decode(r, o, v); }
    case ids::PlayCb::EntityVelocity: { EntityVelocity o; return decode(r, o, v); }
    case ids::PlayCb::Experience: { Experience o; return decode(r, o, v); }
    case ids::PlayCb::Explosion: { Explosion o; return decode(r, o, v); }
    case ids::PlayCb::GameStateChange: { GameStateChange o; return decode(r, o, v); }
    case ids::PlayCb::HeldItemSlot: { HeldItemSlot o; return decode(r, o, v); }
    case ids::PlayCb::KeepAlive: { KeepAlive o; return decode(r, o, v); }
    case ids::PlayCb::KickDisconnect: { KickDisconnect o; return decode(r, o, v); }
    case ids::PlayCb::Login: { Login o; return decode(r, o, v); }
    case ids::PlayCb::Map: { Map o; return decode(r, o, v); }
    case ids::PlayCb::MapChunk: { MapChunk o; return decode(r, o, v); }
    case ids::PlayCb::MultiBlockChange: { MultiBlockChange o; return decode(r, o, v); }
    case ids::PlayCb::NamedEntitySpawn: { NamedEntitySpawn o; return decode(r, o, v); }
    case ids::PlayCb::NamedSoundEffect: { NamedSoundEffect o; return decode(r, o, v); }
    case ids::PlayCb::OpenSignEntity: { OpenSignEntity o; return decode(r, o, v); }
    case ids::PlayCb::OpenWindow: { OpenWindow o; return decode(r, o, v); }
    case ids::PlayCb::PlayerInfo: { PlayerInfo o; return decode(r, o, v); }
    case ids::PlayCb::PlayerlistHeader: { PlayerlistHeader o; return decode(r, o, v); }
    case ids::PlayCb::Position: { Position o; return decode(r, o, v); }
    case ids::PlayCb::RelEntityMove: { RelEntityMove o; return decode(r, o, v); }
    case ids::PlayCb::RemoveEntityEffect: { RemoveEntityEffect o; return decode(r, o, v); }
    case ids::PlayCb::ResourcePackSend: { ResourcePackSend o; return decode(r, o, v); }
    case ids::PlayCb::Respawn: { Respawn o; return decode(r, o, v); }
    case ids::PlayCb::ScoreboardDisplayObjective: { ScoreboardDisplayObjective o; return decode(r, o, v); }
    case ids::PlayCb::ScoreboardObjective: { ScoreboardObjective o; return decode(r, o, v); }
    case ids::PlayCb::ScoreboardScore: { ScoreboardScore o; return decode(r, o, v); }
    case ids::PlayCb::SelectAdvancementTab: { SelectAdvancementTab o; return decode(r, o, v); }
    case ids::PlayCb::SetCooldown: { SetCooldown o; return decode(r, o, v); }
    case ids::PlayCb::SetPassengers: { SetPassengers o; return decode(r, o, v); }
    case ids::PlayCb::SetSlot: { SetSlot o; return decode(r, o, v); }
    case ids::PlayCb::SoundEffect: { SoundEffect o; return decode(r, o, v); }
    case ids::PlayCb::SpawnEntity: { SpawnEntity o; return decode(r, o, v); }
    case ids::PlayCb::SpawnEntityExperienceOrb: { SpawnEntityExperienceOrb o; return decode(r, o, v); }
    case ids::PlayCb::SpawnEntityLiving: { SpawnEntityLiving o; return decode(r, o, v); }
    case ids::PlayCb::SpawnEntityPainting: { SpawnEntityPainting o; return decode(r, o, v); }
    case ids::PlayCb::SpawnEntityWeather: { SpawnEntityWeather o; return decode(r, o, v); }
    case ids::PlayCb::SpawnPosition: { SpawnPosition o; return decode(r, o, v); }
    case ids::PlayCb::Statistics: { Statistics o; return decode(r, o, v); }
    case ids::PlayCb::TabComplete: { TabComplete o; return decode(r, o, v); }
    case ids::PlayCb::Teams: { Teams o; return decode(r, o, v); }
    case ids::PlayCb::TileEntityData: { TileEntityData o; return decode(r, o, v); }
    case ids::PlayCb::Title: { Title o; return decode(r, o, v); }
    case ids::PlayCb::Transaction: { Transaction o; return decode(r, o, v); }
    case ids::PlayCb::UnloadChunk: { UnloadChunk o; return decode(r, o, v); }
    case ids::PlayCb::UnlockRecipes: { UnlockRecipes o; return decode(r, o, v); }
    case ids::PlayCb::UpdateHealth: { UpdateHealth o; return decode(r, o, v); }
    case ids::PlayCb::UpdateTime: { UpdateTime o; return decode(r, o, v); }
    case ids::PlayCb::VehicleMove: { VehicleMove o; return decode(r, o, v); }
    case ids::PlayCb::WindowItems: { WindowItems o; return decode(r, o, v); }
    case ids::PlayCb::WorldBorder: { WorldBorder o; return decode(r, o, v); }
    case ids::PlayCb::WorldEvent: { WorldEvent o; return decode(r, o, v); }
    case ids::PlayCb::WorldParticles: { WorldParticles o; return decode(r, o, v); }
    default: return false;
    }
}

}} // namespace mc::cb
