#!/usr/bin/env python3
"""Generates include/mcscon/blocks_gen.h: per-block flags, exact collision shapes per block state (id<<4|meta) for
ids 0..255 (1.10-1.12.2), and optional names.   usage: gen_blocks.py <data/pc>"""
import json, sys
root = sys.argv[1] + "/1.12"
b = json.load(open(root + "/blocks.json")); cs = json.load(open(root + "/blockCollisionShapes.json"))
flags = [0] * 256; names = [""] * 256; byname = {}
for x in b:
    i = x["id"]; f = 0
    if x["name"] in ("water", "flowing_water", "lava", "flowing_lava"): f |= 2
    if x["transparent"]: f |= 4
    if x["name"] in ("ladder", "vine"): f |= 8
    flags[i] = f; names[i] = x["name"]; byname[x["name"]] = i
shapes = cs["shapes"]; sid = sorted(shapes, key=int)
assert [int(k) for k in sid] == list(range(len(sid)))
boxes = []; table = []
for k in sid:
    table.append((len(boxes), len(shapes[k])))
    for bx in shapes[k]:
        q = [round(c * 32) for c in bx]
        assert all(abs(q[i] / 32 - bx[i]) < 1e-9 for i in range(6)), bx
        boxes.append(q)
perid = [[0] * 16 for _ in range(256)]
for name, v in cs["blocks"].items():
    if name not in byname: continue
    i = byname[name]; perid[i] = [v] * 16 if isinstance(v, int) else (v + [0] * 16)[:16]
uniform = [0xFF] * 256; var = []; varidx = [0] * 256
for i in range(256):
    if len(set(perid[i])) == 1: uniform[i] = perid[i][0]
    else: varidx[i] = len(var); var.append(perid[i])
for i in range(256):
    if uniform[i] == 1: flags[i] |= 1          # Solid: full cube for every meta
    elif uniform[i] != 0xFF and uniform[i] != 0: flags[i] |= 16   # partial collision shape
    elif uniform[i] == 0xFF: flags[i] |= 16
o = ["// GENERATED by tools/gen_blocks.py - do not edit", "#pragma once", '#include "types.h"', "namespace mc { namespace blocks {",
     "enum : u8 { Solid = 1 /*always a full cube*/, Liquid = 2, Transparent = 4, Climbable = 8, PartialShape = 16 /*has collision, not always a full cube*/ };",
     "static const u8 kFlags[256] = {" + ",".join(map(str, flags)) + "};",
     "// Collision shapes: boxes in 1/32 block units (x0,y0,z0,x1,y1,z1), relative to the block corner.",
     "struct Box32 { i8 x0, y0, z0, x1, y1, z1; };",
     "static const Box32 kBoxes[%d] = {%s};" % (len(boxes), ",".join("{%s}" % ",".join(map(str, q)) for q in boxes)),
     "struct ShapeRef { u16 off; u8 n; };",
     "static const ShapeRef kShapes[%d] = {%s};" % (len(table), ",".join("{%d,%d}" % t for t in table)),
     "static const u8 kShapeOfId[256] = {" + ",".join(map(str, uniform)) + "};   // 0xFF: depends on meta, see kShapeOfMeta",
     "static const u8 kVarIndex[256] = {" + ",".join(map(str, varidx)) + "};",
     "static const u8 kShapeOfMeta[%d][16] = {%s};" % (max(1, len(var)), ",".join("{%s}" % ",".join(map(str, v)) for v in var) if var else "{0}"),
     "// shape id for a block state (id << 4 | meta)",
     "inline u8 shapeOf(u16 state) { u8 id = (u8)(state >> 4); if (state >> 12 > 15) return 0; u8 s = kShapeOfId[id]; return s != 0xFF ? s : kShapeOfMeta[kVarIndex[id]][state & 15]; }",
     "#ifdef MCSCON_BLOCK_NAMES", "static const char* const kNames[256] = {" + ",".join('"%s"' % n for n in names) + "};", "#endif",
     "}} // namespace mc::blocks"]
print("\n".join(o))
