#!/usr/bin/env python3
"""Generates tests/zlib_vectors.h: zlib streams (stored/fixed/dynamic/large) + their plaintext hashes."""
import zlib, random
random.seed(7)
def fnv(b):
    h = 2166136261
    for c in b: h = ((h ^ c) * 16777619) & 0xFFFFFFFF
    return h
cases = []
cases.append(("empty", b"", 0))
cases.append(("short", b"hello hello hello minecraft", 9))
cases.append(("stored", bytes(random.randrange(256) for _ in range(3000)), 0))
cases.append(("text", (b"The quick brown fox jumps over the lazy dog. " * 300), 9))
words = [b"stone", b"dirt", b"grass", b"\x00\x01\x02", b"chunk", b"\xff\xfe"]
cases.append(("mixed", b"".join(random.choice(words) * random.randrange(1, 9) for _ in range(20000)), 6))
cases.append(("big", bytes((i * i >> 3) & 0xFF for i in range(300000)), 9))
out = ["// GENERATED by tools/gen_testvec.py", "#pragma once", "#include <stdint.h>", "#include <stddef.h>",
       "struct ZVec { const char* name; const uint8_t* z; size_t zlen; size_t rawlen; uint32_t fnv; };"]
rows = []
for n, raw, lvl in cases:
    z = zlib.compress(raw, lvl)
    out.append(f"static const uint8_t z_{n}[] = {{" + ",".join(map(str, z)) + "};")
    rows.append(f'{{"{n}", z_{n}, {len(z)}, {len(raw)}, {fnv(raw)}u}}')
out.append("static const ZVec zvecs[] = {" + ",".join(rows) + "};")
print("\n".join(out))
