#!/usr/bin/env python3
"""Generates include/mcscon/ids_gen.h from PrismarineJS/minecraft-data protocol.json.
usage: gen_ids.py <minecraft-data>/data/pc > include/mcscon/ids_gen.h
Version-agnostic packet enums + per-version wire-id tables (no dynamic memory, ~1.5KB total)."""
import json, sys, re
root = sys.argv[1]
# (label, data dir, protocol number)
VERS = [("V1_10", "1.10", 210), ("V1_11", "1.11", 315), ("V1_12", "1.12", 335), ("V1_12_2", "1.12.2", 340)]
# 1.11.1/1.11.2 (316) shares 1.11 tables, 1.12.1 (338) shares 1.12.2 tables
def camel(n): return "".join(p.capitalize() for p in n.split("_"))
def load(d, st, dr):
    p = json.load(open(f"{root}/{d}/protocol.json"))[st][dr]["types"]["packet"]
    return {int(k, 16): n for k, n in p[1][0]["type"][1]["mappings"].items()}
STATES = ["handshaking", "status", "login", "play"]
out = ["// GENERATED by tools/gen_ids.py from minecraft-data - do not edit", "#pragma once", "#include \"types.h\"", "namespace mc { namespace ids {", ""]
data = {}
for st in STATES:
    for dr in ("toClient", "toServer"):
        per = {v[0]: load(v[1], st, dr) for v in VERS}
        names = sorted(set().union(*[set(m.values()) for m in per.values()]))
        data[(st, dr)] = (names, per)
        if not names: continue
        e = "".join(w.capitalize() for w in (st, "cb" if dr == "toClient" else "sb"))
        out.append(f"enum class {e} : u8 {{ " + ", ".join(camel(n) for n in names) + f", Count_, Invalid = 0xFF }};")
        out.append(f"#ifdef MCSCON_PACKET_NAMES\nstatic const char* const {e}_names[] = {{" + ",".join('"%s"' % camel(n) for n in names) + "};\n#endif")
        for lab, _ in [(v[0], 0) for v in VERS]:
            m = per[lab]; size = max(m) + 1
            inv = {n: i for i, n in m.items()}
            w2a = [str(names.index(m[i])) if i in m else "0xFF" for i in range(size)]
            a2w = [str(inv[n]) if n in inv else "0xFF" for n in names]
            out.append(f"static const u8 {e}_{lab}_w2a[{size}] = {{{','.join(w2a)}}};")
            out.append(f"static const u8 {e}_{lab}_a2w[{len(names)}] = {{{','.join(a2w)}}};")
        out.append("")
out.append("struct Tables { const u8* w2a; u8 w2aLen; const u8* a2w; u8 a2wLen; };")
for st in STATES:
    for dr in ("toClient", "toServer"):
        names, per = data[(st, dr)]
        if not names: continue
        e = "".join(w.capitalize() for w in (st, "cb" if dr == "toClient" else "sb"))
        out.append(f"static const Tables {e}_tables[{len(VERS)}] = {{" + ",".join(
            f"{{{e}_{v[0]}_w2a,{max(per[v[0]])+1},{e}_{v[0]}_a2w,{len(names)}}}" for v in VERS) + "};")
out.append("}} // namespace mc::ids")
print("\n".join(out))
